#- name: Set Prompt
#  ansible.builtin.shell:
#    set-prompt {{ app_name }}-{{ env }}
#
#- name: Install Nodejs
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: nodejs

- name: Install Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

